// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGdi-bZzCwzVoK9fDOwaNrtcCZ5poxRU',
    appId: '1:245579848431:web:9bc77d5933feb0907d191a',
    messagingSenderId: '245579848431',
    projectId: 'pantrypal-b40e5',
    authDomain: 'pantrypal-b40e5.firebaseapp.com',
    storageBucket: 'pantrypal-b40e5.firebasestorage.app',
    measurementId: 'G-J7GFTE8G9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ere7tZtLI6-HF5541BrpT-TZFnaePfk',
    appId: '1:245579848431:android:2b5b339f819ed7497d191a',
    messagingSenderId: '245579848431',
    projectId: 'pantrypal-b40e5',
    storageBucket: 'pantrypal-b40e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlaVxTb5OhbxdoEv2kvb_NqT9tiqubs_E',
    appId: '1:245579848431:ios:b69701b2711d02c77d191a',
    messagingSenderId: '245579848431',
    projectId: 'pantrypal-b40e5',
    storageBucket: 'pantrypal-b40e5.firebasestorage.app',
    iosBundleId: 'com.example.pantrypal',
  );
}
